apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
  annotations:
    github.com/read-only: 'true'
spec:
  profile:
    displayName: Jenny Doe
    email: jenny-doe@example.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  memberOf: [team-b, employees, roadie]