# Notice the v1beta3 version
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: zip-demo
  title: My custom zip action
  description: scaffolder action to zip the current context?
spec:
  owner: roadie
  type: service

  parameters:
    - title: Create File
      properties:
        path:
          title: Path
          type: string
          default: "."
          description: workspace path to zip
          ui:autofocus: true
          ui:options:
            rows: 5
        content:
          title: File Content
          type: string
          description: content of the file
          ui:autofocus: true
          ui:options:
            rows: 5

    - title: Sleep
      properties:
        amount:
          title: Sleep
          type: number
          description: Amount to sleep in seconds

    - title: Zip
      properties:
        zipPath:
          title: Path
          type: string
          default: "."
          description: workspace path to zip
          ui:autofocus: true
          ui:options:
            rows: 5

  steps:
    - id: createFile
      name: Create File
      action: roadiehq:utils:fs:writeFile
      input:
        path: ${{ parameters.path }}
        content: ${{ parameters.content }}

    - id: sleep
      name: Sleep
      action: roadiehq:utils:sleep
      input:
        amount: ${{ parameters.amount }}

    - id: zip
      name: Zip
      action: roadiehq:utils:zip
      input:
        path: ${{ parameters.zipPath }}

  output:
    path: ${{ steps.zip.output.path }}
