name: E2E Test On PR

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    env:
      CI: true
      NODE_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Log node version
        run: node --version

      - uses: actions/checkout@v2
        with:
         fetch-depth: '0'
      
      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Run tsc
        run: yarn tsc
      
      - name: Run build
        run: yarn build
    
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: CHOKIDAR_USEPOLLING=true yarn dev
          wait-on: 'http://localhost:3000'
          project: ./packages/app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
